---
engines:
  bundler-audit:
    enabled: true
  duplication:
    enabled: false
    config:
      languages:
      - ruby
  fixme:
    enabled: true
    exclude_fingerprints:
    - bd3810225fba5c27540f30702b138804
    - 88fe913ae90e58ac1beb2f8a27eb5520
  rubocop:
    enabled: false
ratings:
  paths:
  - Gemfile.lock
  - "**.rb"
