language: ruby
rvm:
  - 2.3.1
before_install:
  - gem update --system
  - gem --version
script: "bundle exec rspec"
addons:
    code_climate:
        repo_token: 84f6ba29a120bde89aa142fd01af2579321259241675744324b3371eab75e2b2
